services:
  traefik:
    image: traefik:v3
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml'
    networks:
      - traefik-network
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=je.jssouza@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.ciops-demo.duckdns.org`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"

networks:
  traefik-network:
    external: true